Parameters:
  App:
    Type: String
    Description: copilot-nodejs-sample
  Env:
    Type: String
    Description: test
  Name:
    Type: String
    Description: front-end
Resources:
  ddbforcopilotfe:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for ddb-for-copilot-fe'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-${Name}-ddb
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: "S"
        - AttributeName: sort_key
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE

  ddbforcopilotfeAccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the ddb-for-copilot-fe db'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - Grants CRUD access to the Dynamo DB table ${Table}
        - { Table: !Ref ddbforcopilotfe }
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: !Sub ${ ddbforcopilotfe.Arn}
          - Sid: DDBLSIActions
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource: !Sub ${ ddbforcopilotfe.Arn}/index/*

Outputs:
  ddbforcopilotfeName:
    Description: "The name of this DynamoDB."
    Value: !Ref ddbforcopilotfe
  ddbforcopilotfeAccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role."
    Value: !Ref ddbforcopilotfeAccessPolicy